Repository alexearnshaw/making-it-pretty, pull requests merged in 2020-07, with the labels that each got.

#4 Replace the custom styling with bootstrap custom styling using webpack
  _assets/css/_custom.scss
  _assets/css/style.scss
  _assets/js/app.js
  _includes/layouts/base.njk
  _includes/layouts/post.njk
  package.json
  webpack.config.js
Labels: size/M

#5 use npm to run webpack and eleventy in parallel
  netlify.toml
  package.json
Labels: size/S

#2 Create Posts “2020-06-25-small-steps-along-the-road-to-self-service-documentation”
  _site/images/uploads/cms_hackathon.png
  _site/images/uploads/documentation-for-the-kc12fe.jpg
  _site/images/uploads/jekyll.png
  _site/images/uploads/netlify_hackathon.png
  _site/images/uploads/usecms_hackathon.png
  posts/2020-06-25-small-steps-along-the-road-to-self-service-documentation.md
Labels: netlify-cms/draft

#6 work in progress posts
  posts/customize-git-prompt.md
Labels: size/L
